### ISSUE TITLE
[AC] 137 - Cookie.bin

### ISSUE THREAD

**Issue by ArbeyVil** [miffycs/Animal-Crossing-Amiibo#1]
Is not working properly, I I got an error I already try with other files and it still is the same can you please check and let me know if it works for you thank you!

https://github.com/miffycs/Animal-Crossing-Amiibo/blob/master/%5BAC%5D%20137%20-%20Cookie.bin

**Comment by ArbeyVil** [comment]
Try with other files and they works, but ac cookie is no working... :( :(

**Comment by miffycs** [comment]
Hi! This seems to work for me, not sure what the issue might be here.

I don't actually own any of the amiibo files, found them on NFC Bank and just compiled them. Maybe you could download it again or try with another phone?
