### ISSUE TITLE
how do you use tagmo to invite villagers if you dont have nfc tags?

### ISSUE THREAD

**Issue by moongazer07** [miffycs/Animal-Crossing-Amiibo#3]
could you use a phone instead of an tag eg use the phone for different amiibo villagers and you can change the files and reuse by using the nfc feature in a phone

**Comment by kffwlp** [comment]
use the joycon droid app

**Comment by miffycs** [comment]
Hi,

I have not used the joycon droid app mentioned above, so I can't personally speak to whether it works or not.

However, as I explained in the [README](https://github.com/miffycs/Animal-Crossing-Amiibo#cloning-amiibos), part of how this works is we try to imitate the official Nintendo Amiibo cards/figures. What Nintendo does is they lock in character data to the NFC tags within the cards/figures during manufacturing to prevent accidental rewrites/deletions, and apparently this is one of the criteria that the ACNH game checks for when you try and invite a villager. So in my opinion, it's probably better to use the NFC 215 tags.

Hope this helps!
